using System.Collections;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class MiniGame_UITrigger : MonoBehaviour
{
    public GameObject dialogueCanvas;
    public TMP_Text dialogueText;
    public Button nextButton;

    private OVRGrabbable grabbable;
    private bool isDialogueActive = false;
    private int dialogueIndex = 0;

    private string[] dialogueLines = new string[]
    {
        "Ою! ГЏ БИЧЯЗЏ ПЭСсГз АэИЖПі",
        "" // ЕЮ ЙјТА ДыЛчДТ ГЊСпПЁ УЄПя ПЙСЄ
    };

    void Start()
    {
        //  ЗБХИРгПЁ РкЕП ПЌАс
        if (dialogueCanvas == null)
            dialogueCanvas = GameObject.Find("Canvas");

        if (dialogueText == null)
            dialogueText = GameObject.Find("Text (TMP)").GetComponent<TMP_Text>();

        if (nextButton == null)
            nextButton = GameObject.Find("Button").GetComponent<Button>();

        grabbable = GetComponent<OVRGrabbable>();
        dialogueCanvas?.SetActive(false);

        if (nextButton != null)
        {
            nextButton.onClick.AddListener(ShowNextDialogue);
        }
        else
        {
            Debug.LogWarning("Next ButtonРЬ ПЌАсЕЧСі ОЪОвНРДЯДй!");
        }
    }

    void Update()
    {
        if (grabbable == null) return;
        if (!isDialogueActive && grabbable.isGrabbed)
        {
            ShowDialogue();
        }
        else if (isDialogueActive && !grabbable.isGrabbed)
        {
            HideDialogue();
        }
    }

    void ShowDialogue()
    {
        isDialogueActive = true;
        dialogueIndex = 0;
        dialogueCanvas.SetActive(true);
        dialogueText.text = dialogueLines[dialogueIndex];
    }

    void ShowNextDialogue()
    {
        dialogueIndex++;
        if (dialogueIndex < dialogueLines.Length && !string.IsNullOrEmpty(dialogueLines[dialogueIndex]))
        {
            dialogueText.text = dialogueLines[dialogueIndex];
        }
        else
        {
            HideDialogue();
        }
    }

    void HideDialogue()
    {
        dialogueCanvas.SetActive(false);
        isDialogueActive = false;
    }
}
